version: '3'

services: 

  back-end:
    build: 
      context: server
    container_name: back-end
    working_dir: /src/app
    networks: 
      - node-network
    volumes: 
      - ./server:/src/app
      - /src/app/node_modules
    tty: true
    ports: 
      - "8000:8000"
    command: npm run start
    depends_on:
       - db

  front-end:
    build: 
      context: client
    container_name: front-end
    working_dir: /src/app
    networks: 
      - node-network
    volumes: 
      - ./client:/src/app
      - /src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    command: npm run start

  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
    networks: 
      - node-network

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "6000:80"
    networks: 
      - node-network
    depends_on:
       - back-end
       - front-end
  
networks: 
  node-network:
    driver: bridge